# Generated by Django 4.0.4 on 2022-04-15 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_nails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_for_day', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('nails_for_day', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateField(auto_now_add=True, unique_for_date=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='publish')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_pay', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('pay_for_year', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('year', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_for_month', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('medium_pay', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('month', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
