# Generated by Django 4.0.4 on 2022-05-20 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalyticMonth',
            new_name='Analytic_month',
        ),
        migrations.RenameModel(
            old_name='AnalyticYear',
            new_name='Analytic_year',
        ),
    ]
